# Generated by Django 4.2.1 on 2023-05-16 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueId', models.CharField(max_length=50)),
                ('userKey', models.CharField(max_length=50)),
                ('projectKey', models.CharField(max_length=50)),
                ('transitionStatus', models.CharField(choices=[('S', 'Start Work On Issue'), ('E', 'End Work On Issue')], max_length=1)),
                ('transitionTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isLastTransition', models.BooleanField(default=True)),
            ],
        ),
    ]
